source lsb/init-functions, /etc/default/uruk in init script

diff --git a/uruk/init/uruk b/uruk/init/uruk
--- a/uruk/init/uruk
+++ b/uruk/init/uruk
@@ -23,7 +23,8 @@
 ### END INIT INFO
 
 # Copyright (C) 2002, 2003 Laurence J. Lane
-# Copyright (C) 2003, 2004, 2005, 2007, 2010, 2013 Joost van Baal
+# Copyright (C) 2003, 2004, 2005, 2007, 2010 Joost van Baal 
+# Copyright (C) 2013 Joost van Baal-Ilić
 #
 # This file is free software; you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free
@@ -40,8 +41,85 @@
 # Based upon /etc/init.d/iptables as shipped with the Debian iptables
 # package by Laurence J. Lane
 
-set -e
+# /etc/default/uruk can overrule
+# enable_uruk_check, enable_ipv6, enable_autosave, enable_save_counters and PATH
+# On Debian systems, configuration for init scripts is in /etc/default/
+test -f /etc/default/uruk && . /etc/default/uruk
+# On Red Hat systems, configuration for init scripts is in /etc/sysconfig/
+test -f /etc/sysconfig/uruk && . /etc/sysconfig/uruk
 
+###############################################################################
+#
+# This script should be LSB 3.1.0 compliant.  In particular,
+# http://refspecs.freestandards.org/LSB_3.1.0/LSB-generic/LSB-generic/initscrcomconv.html
+# and
+# http://refspecs.freestandards.org/LSB_3.1.0/LSB-generic/LSB-generic/iniscrptact.html
+# should be adhered to:
+# 
+# Error and status messages should be printed with the logging functions (see
+# Init Script Functions) log_success_msg(), log_failure_msg() and
+# log_warning_msg(). Scripts may write to standard error or standard output, but
+# implementations need not present text written to standard error/output to the
+# user or do anything else with it.
+# 
+# LSB required:
+# start   start the service
+# stop    stop the service
+# restart stop and restart the service if the service is already running,
+#         otherwise start the service
+# force-reload   cause the configuration to be reloaded if the service supports
+#         this, otherwise restart the service if it is running
+# status  print the current status of the service
+# 
+# In case of an error while processing any init-script action except for status,
+# the init script shall print an error message and exit with a non-zero status
+# code:
+# 
+# 1   generic or unspecified error (current practice)
+# 2   invalid or excess argument(s)
+# 3   unimplemented feature (for example, "reload")
+# 4   user had insufficient privilege
+# 5   program is not installed
+# 6   program is not configured
+# 7   program is not running
+#
+#
+# Note that those situation shall also be regarded as success:
+# * restarting a service (instead of reloading it)
+#   with the "force-reload" argument
+# * running "start" on a service already running
+# * running "stop" on a service already stopped or not running
+# * running "restart" on a service already stopped or not running
+# * running "try-restart" on a service already stopped or not running
+#
+###############################################################################
+
+
+
+#                        /lib/lsb/init-functions
+# Red Hat EL AS rel 3          Yes
+#
+# Debian GNU/Linux >= Sarge    Yes, in lsb-base package
+#
+# See /usr/share/doc/lsb-core/examples/init-skeleton.gz for sample lsb init
+# script.
+#
+# include lsb functions
+lsb_init_functions=/lib/lsb/init-functions
+uruk_lsb_init_functions=/lib/uruk/lsb/init-functions
+if test -f $lsb_init_functions; then
+  . $lsb_init_functions
+elif test -f $uruk_lsb_init_functions; then
+  . $uruk_lsb_init_functions
+else
+  cat << END
+File $lsb_init_functions nor file $uruk_lsb_init_functions found. Exiting.
+END
+  exit 1
+fi
+
+
+set -e
 
 case "$1" in
   start)
